### ISSUE TITLE
[Feature request] Named backups

### ISSUE THREAD

**Issue by Kristinita** [glutanimate/sublime-create-backup-copy#2]
### 1. Request

It would be nice, if would be possible to create named backups.

### 2. Justification

For example, I write working code in a file. I wrote working code and I save my file. Then I continue to write the code in a file → my code doesn't work. I want to see version of my file with working code, that

1. I can to diff between current and working versions of my file,
1. I can revert my file to working versions.

Sublime Text users have packages for Automatic Backups — [**Local History**](https://github.com/vishr/local-history) for example, — but none of them can do named backups. It difficult to understand which of the saved versions of the file is working without human-created filenames.

### 3. Desirable behavior

☐ I write working code → <kbd>Ctrl+Shift+P</kbd> → `Create Backup Copy: Create Named Backup` → quick panel shown for me → I wrote in quick panel custom name of my backup copy → <kbd>Enter</kbd> → named copy successful saved for me.
☐ I want to see named copy. I open the file I backup → `Create Backup Copy: Open Named Backup` → I see quick panel with all named backups of my file → I select named backup → named backup open for me.

Thanks.

**Comment by glutanimate** [comment]
Hi @Kristinita,

thanks for taking the time to submit this feature request.

I really like the idea of adding named backups to the plugin, but as I am swamped with my studies and other projects I'm afraid I won't be able to implement this anytime soon.

I'd be more than happy to accept a PR, though!

**Comment by Kristinita** [comment]
Behavior [**implemented to Local History**](https://github.com/vishr/local-history/issues/92#issuecomment-338648220).

Thanks.
